//
//  SLConstants.c
//  Send Location To Server
//
//  Created by Mixaill Anatolich on 6/22/13.
//  Copyright (c) 2013 Mixaill Anatolich. All rights reserved.
//

NSString * const UPDATE_LOCATION_NOTIFICATION = @"UPDATE_LOCATION_NOTIFICATION";
NSString * const SEND_LOCATION_NOTIFICATION = @"SEND_LOCATION_NOTIFICATION";

NSString * const SEND_LOCATION_ENABLED = @"SEND_LOCATION_ENABLED";

NSString * const SERVER_NAME_SETTING = @"SERVER_NAME_SETTING";
NSString * const TYPE_OF_REQUEST_SETTING = @"TYPE_OF_REQUEST_SETTING";
NSString * const TYPE_OF_HTTP_METHOD_SETTING = @"TYPE_OF_HTTP_METHOD_SETTING";
NSString * const DEVICE_ID_SETTING = @"DEVICE_ID_SETTING";
NSString * const ACCOUNT_ID_SETTING = @"ACCOUNT_ID_SETTING";
NSString * const SEND_DEVICE_ID_SETTING = @"SEND_DEVICE_ID_SETTING";
NSString * const SEND_ACCOUNT_ID_SETTING = @"SEND_ACCOUNT_ID_SETTING";
NSString * const ADDITIONAL_PARAMETERS_SETTING = @"ADDITIONAL_PARAMETERS_SETTING";

NSString * const SEND_LOCATION_IN_BACKGROUND_SETTING = @"SEND_LOCATION_IN_BACKGROUND_SETTING";
NSString * const NOT_TURN_OFF_DISPLAY_SETTING = @"NOT_TURN_OFF_DISPLAY_SETTING";
NSString * const LOGGIN_INTERVAL_SETTING = @"LOGGIN_INTERVAL_SETTING";


int const DEFAULT_LOGGIN_INTERVAL = 60;


NSString * const NOT_FIRST_START = @"NOT_FIRST_START";